In [110]:
import sys
import numpy as np
import pandas as pd
from numpy import linalg as lin
import matplotlib.pyplot as plt


In [111]:
# def _import_data
path = 'data1.txt'
data1=pd.read_csv(path,header=None, names=['x1','x2','x3','y'])
data1.head()

x1  x2  x3  y
0   1  -1   2  1
1   1   1   3  4
2  -1   1   0 -1
3   1   2  -4 -2
4   3  -1  -1  0

In [112]:
#data preprocess
data1.insert(0,'ones',1)
data1.head()

ones  x1  x2  x3  y
0     1   1  -1   2  1
1     1   1   1   3  4
2     1  -1   1   0 -1
3     1   1   2  -4 -2
4     1   3  -1  -1  0

In [113]:
# print(theta)
# theta[0,1]=2
# print(theta)

In [114]:
#traniing preprocess
cols=data1.shape[1]
x = data1.iloc[:,0:cols-1]
y = data1.iloc[:,cols-1:cols]
x = np.matrix(x.values)
y = np.matrix(y.values)
# theta = np.matrix(np.zeros(4))
theta=np.matrix([0.0,0.0,0.0,0.0])
print(x.shape,y.shape,theta.shape,len(x))

(5, 4) (5, 1) (1, 4) 5


In [115]:
#define cost 
def computeCost(x,y,theta):
    innerCost=np.power((y-x * theta.T),2)
    sumCost=(np.sum(innerCost)/2)
    return sumCost

In [117]:
# define the gradient
def gradientDescent(x,y,theta,alpha,iters):
    temp=theta
    parameters = 4
    cost=np.zeros(iters)
    grad=np.zeros(parameters)
    for i in range(iters):
        error = y-x * theta.T
        for j in range(parameters):
            grad[j] = -np.sum(np.multiply(error,x[:,j]))
            temp[0,j]=theta[0,j]-alpha * grad[j]
        theta=temp
        cost[i]=computeCost(x,y,theta)
    return cost[iters-1],theta
                


In [126]:
#stochastic gradient
def gradientDescent(x,y,theta,alpha,i):
    temp=theta
    parameters = 4
    cost=np.zeros(i)
    grad=np.zeros(parameters)
    error = y-x * theta.T
    for j in range(parameters):
        grad[j] = error[i] * x[i,j]
        temp[0,j]=theta[0,j]-alpha * grad[j]
    print(grad,'grad')
    theta=temp
    cost=computeCost(x,y,theta)
    return cost,theta

In [127]:
#perfrom linear regression and get the error
theta=np.matrix([0.0,0.0,0.0,0.0])
alpha=0.1
print(theta)
for i in range(5):
    costFinal,theta=gradientDescent(x,y,theta,alpha,i)
    print(costFinal,theta,"costFinal,theta")

[[0. 0. 0. 0.]]
[ 1.  1. -1.  2.] grad
17.060000000000002 [[-0.1 -0.1  0.1 -0.2]] costFinal,theta
[ 4.7  4.7  4.7 14.1] grad
87.6681 [[-0.57 -0.57 -0.37 -1.61]] costFinal,theta
[-0.63  0.63 -0.63 -0.  ] grad
88.38100800000001 [[-0.507 -0.633 -0.307 -1.61 ]] costFinal,theta
[ -6.686  -6.686 -13.372  26.744] grad
413.58778056000006 [[ 0.1616  0.0356  1.0302 -4.2844]] costFinal,theta
[ -3.5226 -10.5678   3.5226   3.5226] grad
472.7118527964002 [[ 0.51386  1.09238  0.67794 -4.63666]] costFinal,theta
